FROM python:3.8

RUN pip3 --no-cache-dir install scrapy-crawlera

RUN scrapy startproject client &&\
    printf "\
DOWNLOADER_MIDDLEWARES = {'scrapy_crawlera.CrawleraMiddleware': 610} \n\
ROBOTSTXT_OBEY = False \n\
" >> client/client/settings.py

COPY client-scrapy.py client/client/spiders/

CMD bash -c "cd client; scrapy crawl client; test -e /GOTIT"
