FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /client

ENV DOTNET_CLI_TELEMETRY_OPTOUT=true
RUN dotnet -d new console && rm -rf obj Program.cs

COPY client.cs .
RUN dotnet -d publish -c Release -r linux-musl-x64 -p:PublishSingleFile=true

FROM alpine:3.13

RUN apk --no-cache add icu-libs krb5-libs ca-certificates

COPY zyte-smartproxy-ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

COPY --from=0 /client/bin/Release/net5.0/linux-musl-x64/publish/client /

CMD /client
