FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ENV PATH=$PATH:/root/.dotnet/tools
RUN dotnet tool install -g dotnet-script

COPY crawlera-ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

COPY client.csx /
RUN dotnet script publish client.csx 

CMD /publish/linux-x64/client
