FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN dotnet tool install -g dotnet-script
ENV PATH=$PATH:/root/.dotnet/tools

COPY client.csx /
RUN dotnet script publish client.csx 

CMD /publish/linux-x64/client
