FROM openjdk:14-alpine

ARG ZYTE_CA
ADD $ZYTE_CA .
RUN keytool -noprompt -import -file zyte-smartproxy-ca.crt -storepass changeit -cacerts

COPY client.java .
RUN javac client.java

CMD java -Djdk.http.auth.tunneling.disabledSchemes= client
