FROM python:3.10

RUN pip3 --no-cache-dir install scrapy-zyte-smartproxy

RUN scrapy startproject client &&\
    printf "\
DOWNLOADER_MIDDLEWARES = {'scrapy_zyte_smartproxy.ZyteSmartProxyMiddleware': 610} \n\
ROBOTSTXT_OBEY = False \n\
" >> client/client/settings.py

COPY client-scrapy.py client/client/spiders/

CMD bash -c "cd client; scrapy crawl client; test -e /GOTIT"
