FROM r-base:4.1.1

RUN apt-get update && apt-get -y install libssl-dev libcurl4-openssl-dev

RUN MAKEFLAGS=-j4 Rscript -e "install.packages('httr')"

ARG ZYTE_CA
ADD $ZYTE_CA .
COPY client.R .

CMD Rscript client.R
